server:
  #port: 8088

spring:
  application:
    name: TownSq-Backend-Tech-Challenge

  datasource:
    url: jdbc:h2:mem:townsq-db
    driver-class-name: org.h2.Driver
    username: sa
    password: '123'
    platform: h2
  
  h2:
    console.enabled: 'true'
    path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create    # This will recreate the schema each time
    defer-datasource-initialization: true    # Important! This ensures data.sql runs after Hibernate initialization
    show-sql: 'true'
  sql:
    init:
      mode: always    # Ensures SQL initialization is performed

logging:
  level:
    org:
      springframework: INFO